### ISSUE TITLE
Unable to use npm in prepare_cmd

### ISSUE THREAD

**Issue by rthaut** [dropseed/nextrelease#8]
I am attempting to use `npm version` in the `prepare_cmd`, but the step fails with the message:

```
/bin/sh: 2: npm: not found
```

I am using GitHub's `actions/setup-node@v2` action to install node and npm, but that doesn't seem to have made a difference.

Here's the larger output from the git action based on [this nextrelease.yml](https://github.com/rthaut/text-utils-browser-extension/blob/master/.github/workflows/nextrelease.yml):
```
Run dropseed/nextrelease@v1
  with:
    prepare_cmd: sed -i -e "s/v$LAST_VERSION/v$NEXT_VERSION/g" README.md
  npm version $NEXT_VERSION --git-tag-version=false
  
    publish_cmd: git tag -a v$VERSION_MAJOR -m Version $VERSION_MAJOR -f && git push origin v$VERSION_MAJOR -f
  
    github_token: ***
    tag_prefix: v
    next_branch: nextrelease
/usr/bin/docker run --name e1cc5135a9ff23e189439994e5130152ae4b9c_0aa3e1 --label e1cc51 --workdir /github/workspace --rm -e INPUT_PREPARE_CMD -e INPUT_PUBLISH_CMD -e INPUT_GITHUB_TOKEN -e INPUT_TAG_PREFIX -e INPUT_NEXT_BRANCH -e TAG_PREFIX -e NEXT_BRANCH -e PUBLISH_CMD -e PREPARE_CMD -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/text-utils-browser-extension/text-utils-browser-extension":"/github/workspace" e1cc51:35a9ff23e189439994e5130152ae4b9c
Switched to a new branch 'nextrelease'
Branch 'nextrelease' set up to track remote branch 'nextrelease' from 'origin'.
/bin/sh: 2: npm: not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nextrelease/__main__.py", line 4, in <module>
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
tag_prefix: v
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cls_client/client.py", line 72, in wrapper
    raise raised_exception
  File "/usr/local/lib/python3.9/site-packages/cls_client/client.py", line 57, in wrapper
    return_value = func(*args, **kwargs)
  File "/nextrelease/cli.py", line 178, in ci
    subprocess.check_call(
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sed -i -e "s/v$LAST_VERSION/v$NEXT_VERSION/g" README.md
npm version $NEXT_VERSION --git-tag-version=false
' returned non-zero exit status 127.
api_url: https://api.github.com
next_branch: nextrelease
publish_cmd: git tag -a v$VERSION_MAJOR -m Version $VERSION_MAJOR -f && git push origin v$VERSION_MAJOR -f

prepare_cmd: sed -i -e "s/v$LAST_VERSION/v$NEXT_VERSION/g" README.md
npm version $NEXT_VERSION --git-tag-version=false
```

**Comment by davegaeddert** [comment]
Hmm. I'm not sure off the top of my head but I'll see if I can fork your repo and give it a try too.

**Comment by davegaeddert** [comment]
So, evidently the `$PATH` does not get passed through to a docker action. I haven't used this for npm yet myself (and nobody has reported this until now), but I think the other examples work because they use more standard bin paths... 

Inside the action:
![CleanShot 2021-10-01 at 16 45 35](https://user-images.githubusercontent.com/649496/135689572-9f1d1ce3-8a9e-4125-969d-03992e1ade52.png)

Outside the action:
![CleanShot 2021-10-01 at 16 45 54](https://user-images.githubusercontent.com/649496/135689597-1bd7dcf7-71db-4ffa-a2c6-74f100be911a.png)

I'll try to get a fix in place!
